baseurl: "https://faangtalk.github.io"
title: "FaangTalk"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "docs"
paginate: 50
uglyURLs: false
metaDataFormat: "yaml"
LanguageCode: ru
params:
  itunes: https://podcasts.apple.com/podcast/id6736882581
  android: https://www.youtube.com/watch?v=PYZVfTor2hM&list=PLNLPaBDVlFrME0ua6ZI9ce6fHMjmdkjrq
  feed: /index.xml
  yandex: https://music.yandex.ru/album/{id}
  desc: Подкаст о систем дизайне в компании FAANG
  summary: Изучаем систем дизайн, архитектуру и алгоритмы
  StaticURL: "https://faangtalk.org"
  LanguageCode: ru
  yandexS3: "https://storage.yandexcloud.net/faangtalk/"
permalinks:
  post: "/:title"
markup:
  goldmark:
    renderer:
      unsafe: true


